// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVd1uofFMWMcQiQlTqWmt3YmUc7rkoZ04',
    appId: '1:1000419828114:web:ac94b33a25ef63c98e214b',
    messagingSenderId: '1000419828114',
    projectId: 'adddetails-95682',
    authDomain: 'adddetails-95682.firebaseapp.com',
    storageBucket: 'adddetails-95682.appspot.com',
    measurementId: 'G-99LF22C5GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjQeWwrLWeH1uchdmRzjglYilElNOcOM',
    appId: '1:1000419828114:android:79655eebf53ce60c8e214b',
    messagingSenderId: '1000419828114',
    projectId: 'adddetails-95682',
    storageBucket: 'adddetails-95682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvslmhWl2kt7Rz2iRnRJUJXC9YF2eqbLo',
    appId: '1:1000419828114:ios:9667423add3508bf8e214b',
    messagingSenderId: '1000419828114',
    projectId: 'adddetails-95682',
    storageBucket: 'adddetails-95682.appspot.com',
    iosBundleId: 'com.example.addDetals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvslmhWl2kt7Rz2iRnRJUJXC9YF2eqbLo',
    appId: '1:1000419828114:ios:1577378d4ed0b32f8e214b',
    messagingSenderId: '1000419828114',
    projectId: 'adddetails-95682',
    storageBucket: 'adddetails-95682.appspot.com',
    iosBundleId: 'com.example.addDetals.RunnerTests',
  );
}
